CREATE DATABASE HOUSE_HUNTER

CREATE TABLE HOUSE(
 ID INT NOT NULL IDENTITY(1,1),
 LONGITUDE INT NOT NULL,
 LATITUDE  INT NOT NULL,
 ADDRESS VARCHAR(120),
 BUY_PRICE FLOAT NULL,
 RENT_PRICE FLOAT NULL,
 DESCRIPTION VARCHAR(255),
 CONSTRAINT PK_HOUSE PRIMARY KEY(ID)
)

CREATE TABLE CONTACT(
	ID INT NOT NULL IDENTITY(1,1),
	ID_HOUSE INT NOT NULL,
	TYPE VARCHAR(50) NOT NULL,
	VALUE_CONTACT VARCHAR(60) NOT NULL

	CONSTRAINT PK_CONTACT PRIMARY KEY(ID),
	CONSTRAINT FK_CONTACT_HOUSE FOREIGN KEY(ID_HOUSE) REFERENCES HOUSE(ID)
)


CREATE TABLE COMFORTABLE(
	ID INT NOT NULL IDENTITY(1,1),
	NAME VARCHAR(60),
	CONSTRAINT PK_COMFORTABLE PRIMARY KEY(ID),

)

CREATE TABLE HOUSE_COMFORTABLE(
	ID_HOUSE INT NOT NULL,
	ID_COMFORTABLE INT NOT NULL,
	QUANTITY INT NOT NULL
	CONSTRAINT PK_HOUSE_COMFORTABLE_HOUSE FOREIGN KEY(ID_HOUSE) REFERENCES HOUSE(ID),
	CONSTRAINT PK_HOUSE_COMFORTABLE_COMFORTABLE FOREIGN KEY(ID_COMFORTABLE) REFERENCES COMFORTABLE(ID)
	)


